

export const REQUEST_PENDING = "REQUEST_PENDING";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";








